version: "3.7"

services:

  dat-db:
    image: postgres:11.6
    ports:
      - "5435:5432"
    networks:
      - stock-net
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=stock
    volumes:
      - ./dump/:/docker-entrypoint-initdb.d/
      - stock-db:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  stock-net:

volumes:
  stock-db: