version: '3.8'
services:
  dat-db:
    image: postgres:11.6
    ports:
      - "5435:5432"
    networks:
      - dat-net
    environment:
      - POSTGRES_PASSWORD=PVYG2U2pZeBA3Aqp
      - POSTGRES_USER=curator
      - POSTGRES_DB=curatordb
    volumes:
      - ./dump/:/docker-entrypoint-initdb.d/
      - v-dat-db:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  dat-net:

volumes:
  v-dat-db: